# This is a basic workflow to help you get started with Actions

name: prerelease

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [release, hotfix]
  # Remove this before deploy
  pull_request:
    branches: [develop]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  prerelease:
    name: Development Release
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: dart --version
      - run: flutter --version      
      - name: Edit pubspec.ymal for dev release
        run: |
          sed  -i "s/version.*/&-$GITHUB_RUN_ID/" pubspec.yaml
      - name: Get Changelog Entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2.0.0
      - name: Edit changelog.md for dev release
        run: |
          sed -i "s/##[*/&-$steps.changelog_reader.outputs.version/" changelog.md
          echo changelog.md
